### ISSUE TITLE
Line breaks in Markdown don't count as a space

### ISSUE THREAD

**Issue by tigerros** [DioxusLabs/include_mdbook#3]
See https://github.com/DioxusLabs/docsite/issues/126

**Comment by FlippingBinary** [comment]
This is all new to me, but it looks like the [pulldown_cmark](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/index.html) library sends a `Start` event at the start of a paragraph, followed by `Text` for each line of the paragraph, followed by an `End` event when the paragraph ends. 

Perhaps the `Event::Text` handler...

https://github.com/DioxusLabs/include_mdbook/blob/7b3f3e70701af8da2b25a52703297c2dd0bdbb91/mdbook-macro/src/rsx.rs#L73-L75

... could check for an existing `BodyNode::Text` it can append to before creating a new text node? I'm not sure if those nodes can be appended to, but if not they should be replaceable, so the last one could be popped off so the text can be extracted and concatenated with the new text before calling `create_node`.

Am I on the right track?

**Comment by ealmloff** [comment]
> This is all new to me, but it looks like the [pulldown_cmark](https://docs.rs/pulldown-cmark/latest/pulldown_cmark/index.html) library sends a `Start` event at the start of a paragraph, followed by `Text` for each line of the paragraph, followed by an `End` event when the paragraph ends.
> 
> Perhaps the `Event::Text` handler...
> 
> https://github.com/DioxusLabs/include_mdbook/blob/7b3f3e70701af8da2b25a52703297c2dd0bdbb91/mdbook-macro/src/rsx.rs#L73-L75
> 
> ... could check for an existing `BodyNode::Text` it can append to before creating a new text node? I'm not sure if those nodes can be appended to, but if not they should be replaceable, so the last one could be popped off so the text can be extracted and concatenated with the new text before calling `create_node`.
> 
> Am I on the right track?

Yes, that sounds correct. It should be possible to modify the last text node on the [element stack](https://github.com/DioxusLabs/include_mdbook/blob/7b3f3e70701af8da2b25a52703297c2dd0bdbb91/mdbook-macro/src/rsx.rs#L46) if it exists instead of creating a new text node
